services:
  - type: web
    name: petly-backend
    env: python
    buildCommand: pip install -r back_end/requirements.txt
    startCommand: gunicorn back_end.app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: petly-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: petly-db
    databaseName: petly_db
    user: petly_user
